### ISSUE TITLE
Big Sur binary?

### ISSUE THREAD

**Issue by turian** [lostjared/Acid.Cam.v2.OSX#8]
Hi! Chemical Adam recommended I use your package. Could you release a Big Sur binary? I am on 11.6.7

**Comment by lostjared** [comment]
I use the current version on BigSur check the releases section on this repo. Also you will have to poke a hole in Gatekeeper for it to run. In the Security and privacy section of the macOS settings app.  https://www.howtogeek.com/205393/gatekeeper-101-why-your-mac-only-allows-apple-approved-software-by-default/
